v2.3.0 for nats migration and last bionic
[Migration Release]

The purpose of this release is to provide a step to migrate to v3.0.0.
This works by the following method:

* This version starts using the nats mbus certs instead of username and
  password, which becomes mandatory in bosh v274.0.0.  These certs were
  installed several releases ago, but were not in use.  They must be in
  use before upgrading beyond this version

* Once deployed, each deployment under the bosh director will need to
  get recreated(`genesis <env> deploy --recreate`) in order to propagate
  the nats changes.

* You can then upgrade to v3.0.0, and then recreate the deployments
  under the director once again to finalize the upgrade.

This is also the last verison to support bionic stemcells.  It also
supports jammy, using the feature `jammy` to turn it on.  Unfortunately,
there are no precompiled releases other than bosh-v273.1.0 for bionic,
so those will be built from source if using the default bionic
configuration.

diff --git a/ci/scripts/pull-upstream b/ci/scripts/pull-upstream
--- a/ci/scripts/pull-upstream
+++ b/ci/scripts/pull-upstream
@@ -1,6 +1,8 @@
 #!/bin/bash
 set -eu
-package="$UPSTREAM_PATH"
+package="$UPSTREAM_REPO"
+local_path="${UPSTREAM_PATH:-$package}"
+
 github_org="cloudfoundry"
 boshio_org="cloudfoundry"
 
@@ -15,7 +17,7 @@ version="${1:-}"
 
 set -ue
 # go to base directory
-[[ -d "$UPSTREAM_PATH" ]] || error "Could not find upstream directory under base path $(pwd)"
+[[ -d "$local_path" ]] || error "Could not find upstream directory under base path $(pwd)"
 
 workdir=$(mktemp -d 2>/dev/null || mktemp -d -t 'mytmpdir')
 [[ -n "$workdir" ]] && [[ -d "$workdir" ]] || error "Failed to make work directory"
@@ -33,10 +35,10 @@ git_commit="$(git rev-parse --short HEAD 2>/dev/null || echo '')"
 [[ -n "$git_commit" ]] || error "Failed to fetch ${package} v${version} -- cannot continue"
 popd >/dev/null 2>&1
 
-rm -rf "${package}"
+rm -rf "${local_path}"
 src="$workdir/${package}"
-cp -R "$src" "$package"
-rm -rf "${package}/tests" "${package}/ci" "${package}/.git"
+cp -R "$src" "$local_path"
+rm -rf "${local_path}/tests" "${local_path}/ci" "${local_path}/.git"
 rm -rf "$workdir"
 
 if [[ -n "$(git status --porcelain)" ]] ; then
