Transitioned RN gist to git repo
The storage of the Release Notes as a gist worked fine, but gists are
only editable by the user who created them (not available for orgs).
Moving to a genesis-community org repo to hold the pre-edited release
notes.

In shipit, we detect that the release notes are for the correct version
now, and error if they are not.  If it is a match, we purge the raw
commits and version trace comment before using it as the release body.

Also fixed some typos

diff --git a/ci/scripts/shipit b/ci/scripts/shipit
--- a/ci/scripts/shipit
+++ b/ci/scripts/shipit
@@ -65,7 +65,18 @@ cat > "${RELEASE_ROOT}/notification" <<EOF
 EOF
 
 header "Release Notes for v${VERSION}"
-cat "${RELEASE_NOTES_PATH}"
+header="$(sed -i -e '1{w /dev/stdout' -e 'd}' "${RELEASE_NOTES_PATH}")"
+re="^<!--- Release Notes for v${VERSION} -- Do not move --->$"
+if [[ "$header" =~ $re ]] ; then
+  sed -i  '/^---8<--- This line and everything below will be ignored ---8<---$/,$d' "${RELEASE_NOTES_PATH}"
+  cat "${RELEASE_NOTES_PATH}"
+else
+  echo "Failed to find release notes for v$VERSION in $RELEASE_NOTES_PATH.  Found this instead:"
+  echo
+  echo "$header"
+  cat "${RELEASE_NOTES_PATH}"
+  exit 1
+fi
 
 header "Fast-forward merge develop into ${RELEASE_BRANCH}"
 pushd git-main &>/dev/null
