WIP: Fix pipeline test for detected features

diff --git a/ci/scripts/test b/ci/scripts/test
--- a/ci/scripts/test
+++ b/ci/scripts/test
@@ -8,32 +8,40 @@ SKIP_SMOKE_TESTS=${SKIP_SMOKE_TESTS:-"false"}
 SKIP_CLEAN=${SKIP_CLEAN:-"false"}
 
 header() {
-	echo
-	echo "###############################################"
-	echo
-	echo "$1"
-	echo
+  echo
+  echo "================================================================================"
+  echo "$1"
+  echo "--------------------------------------------------------------------------------"
+  echo
+}
+
+has_feature() {
+	genesis lookup "$1" kit.features 2>/dev/null | jq -e --arg feature "$2" '. | index($feature)' >/dev/null
+}
+
+is_proto() {
+	has_feature $1 'proto' # This will need to be changed in v2.8.0
 }
 
 cleanup_environment() {
 	env="$1"
-  if [[ -f .genesis/manifests/$env-state.yml ]] ; then
-    header "Preparing to delete proto environment $DEPLOY_ENV"
-    echo "Generating reference manifest..."
-    genesis manifest "$env" --no-redact > manifest.yml
-    echo $'\n'"Building BOSH variables file..."
-    genesis lookup --merged "${env}" bosh-variables > vars.yml
-    echo $'\n'"$env state file:"
-    echo "----------------->8------------------"
-    cat ".genesis/manifests/$env-state.yml"
-    echo "----------------->8------------------"
-    header "Deleting $DEPLOY_ENV environment..."
-    $BOSH delete-env --state ".genesis/manifests/$env-state.yml" --vars-file vars.yml manifest.yml
-    rm manifest.yml
-    rm vars.yml
-  else
-    echo "Cannot clean up previous $env environment - no state file found"
-  fi
+	if [[ -f .genesis/manifests/$env-state.yml ]] ; then
+		header "Preparing to delete proto environment $env"
+		echo "Generating reference manifest..."
+		genesis manifest "$env" --no-redact > manifest.yml 2>/dev/null
+		echo $'\n'"Building BOSH variables file..."
+		genesis lookup --merged "${env}" bosh-variables > vars.yml 2>/dev/null
+		echo $'\n'"$env state file:"
+		echo "----------------->8------------------"
+		cat ".genesis/manifests/$env-state.yml"
+		echo "----------------->8------------------"
+		header "Deleting $DEPLOY_ENV environment..."
+		$BOSH delete-env --state ".genesis/manifests/$env-state.yml" --vars-file vars.yml manifest.yml
+		rm manifest.yml
+		rm vars.yml
+	else
+		echo "Cannot clean up previous $env environment - no state file found"
+	fi
 }
 
 cleanup_deployments() {
@@ -49,17 +57,13 @@ cleanup_deployments() {
 
 cleanup() {
 	for deployment in "$@"; do
-		bosh_env="$(genesis lookup --exodus "$DEPLOY_ENV" "bosh" "(none)" 2>/dev/null)"
-		if [[ "$bosh_env" == "(none)" ]] ; then
+		if is_proto "$deployment" ; then
 			cleanup_environment "$deployment"
 		else
 		  cleanup_deployment "$deployment-${KIT_SHORTNAME}"
 		fi
 	done
 }
-
-header "Checking previous deployments on ${BOSH_ENVIRONMENT}..."
-$BOSH deployments
 
 header "Pre-test Cleanup"
 if [[ "$SKIP_FRESH" == "false" ]]; then
@@ -88,29 +92,34 @@ if [[ "$SKIP_DEPLOY" == "false" ]]; then
 	genesis add-secrets "${DEPLOY_ENV}"
 	genesis deploy -y "${DEPLOY_ENV}"
 
+	if [[ -f .genesis/manifests/${DEPLOY_ENV}-state.yml ]] ; then
+		echo $'\n'"${DEPLOY_ENV} state file:"
+		echo "----------------->8------------------"
+		cat ".genesis/manifests/${DEPLOY_ENV}-state.yml"
+		echo "----------------->8------------------"
+	fi
+
 	genesis info "${DEPLOY_ENV}"
 
 	header "Validating addons..."
 	genesis "do" "${DEPLOY_ENV}" -- login
 	genesis "do" "${DEPLOY_ENV}" -- credhub-login
-	genesis "do" "${DEPLOY_ENV}" -- vault-proxy-login
+	if has_feature "${DEPLOY_ENV}" "vault-credhub-proxy" ; then
+		genesis "do" "${DEPLOY_ENV}" -- vault-proxy-login
+	fi
 	safe target "$safe_target_orig"
 
-	$BOSH -d "${DEPLOY_ENV}-$KIT_SHORTNAME" instances --ps
+	if ! is_proto "$DEPLOY_ENV" ; then
+		$BOSH -d "${DEPLOY_ENV}-$KIT_SHORTNAME" instances --ps
+	fi
 
-  if [[ -f .genesis/manifests/${DEPLOY_ENV}-state.yml ]] ; then
-    echo $'\n'"${DEPLOY_ENV} state file:"
-    echo "----------------->8------------------"
-    cat ".genesis/manifests/${DEPLOY_ENV}-state.yml"
-    echo "----------------->8------------------"
-  fi
 fi
 
 if [[ "$SKIP_SMOKE_TESTS" == "false" ]]; then
 	header "Validating ${DEPLOY_ENV} BOSH director admin / concourse UAA credentials..."
 	(
-		BOSH_CA_CERT="$(safe read "secret/$vault_path/$KIT_SHORTNAME/ssl/ca:certificate")"
-		BOSH_ENVIRONMENT="$(genesis lookup --exodus "$DEPLOY_ENV}" url 2>/dev/null)"
+		BOSH_CA_CERT="$(genesis lookup --exodus "$DEPLOY_ENV" ca_cert 2>/dev/null)"
+		BOSH_ENVIRONMENT="$(genesis lookup --exodus "$DEPLOY_ENV" url 2>/dev/null)"
 		export BOSH_CA_CERT
 		export BOSH_ENVIRONMENT
 
@@ -123,7 +132,10 @@ if [[ "$SKIP_SMOKE_TESTS" == "false" ]]; then
 		$BOSH env
 	)
 
-	 genesis "do" "${DEPLOY_ENV}" -- smoketests
+	# TODO: need an actual smoke-test, but this doesn't exist yet...
+	#if ! is_proto "$DEPLOY_ENV" ; then
+	#	genesis "do" "${DEPLOY_ENV}" -- smoketests
+	#fi
 else
 	echo "Skipping smoke_tests"
 fi
