[ci] fix more ci updates for gcp

diff --git a/ci/scripts/test-deployment b/ci/scripts/test-deployment
--- a/ci/scripts/test-deployment
+++ b/ci/scripts/test-deployment
@@ -77,15 +77,19 @@ else
 	echo "Skipping cleaning up from any previous deploy"
 fi
 
-cat <<EOF > get-env.pl
+cat <<'EOF' > get-env.pl
 #!/usr/bin/env perl
 use lib "$ENV{HOME}/.geese/lib";
 use JSON::PP qw/encode_json/;
 print encode_json(\%ENV);
 EOF
-chmod get-env.pl
+chmod +x "get-env.pl"
 vault_path="$(genesis sh "${DEPLOY_ENV}" -s "$(pwd)/get-env.pl" | grep '^{' | jq -r '.GENESIS_SECRETS_BASE')"
 vault_path="${vault_path%/}" # trim any trailing slash
+if [[ -z "$vault_path" ]] ; then
+  echo >&2 "Failed to determine vault path.  Cannot continue!"
+  exit 2
+fi
 
 if [[ "$SKIP_REPLACE_SECRETS" == "false" ]] ; then
 	safe rm -rf "$vault_path"
