Allow for download and upload of stemcell files
`upload-stemcells` works fine when the bosh director could reach the
internet (except for the bugs in the last release).  However, if the
bosh director didn't have access to the internet due to network
configuration, intentional or otherwise, you couldn't get stemcells onto
it.

This commit adds a --dl flag to download the selected or specified
stemcells and then upload the local file.  It also added --dry-run if
you just want to show the url and sha1 for the files for use downloading
it in another manner.

In addition, to support mass-uploading to different directors without
mass-downloading, `download-stemcells` was added with the same selection
or specification interface as upload-stemcells, so you could download a
set of stemcells.  `upload-stemcells` was also updated to accept a
relative file location as a candidate to upload to allow you to upload
the downloaded stemcell files.

diff --git a/hooks/addon b/hooks/addon
--- a/hooks/addon
+++ b/hooks/addon
@@ -59,148 +59,9 @@ login() {
     bosh -e "$GENESIS_ENVIRONMENT" login
 }
 
-upload_stemcell() {
-  local url sha1 os="$1" cpi="$2" version="$3" fix="$4" data="$5" type="$6" noupload="$7"
-  read -r url sha1 <<< "$(jq -r --arg t "$type" --arg v "$version" '.[] | select(.version == $v)| to_entries[] | select(.key == $t).value  | .url + " " + .sha1' <<<"$data")"
-  [[ "$type" == "regular" ]] && type="full"
-  if [[ -n "$noupload" ]] ; then
-    describe "" \
-      "#G{Details for selected}#C{$type}#G{ stemcell}:" \
-      "  * CPI:     #c{$cpi}" \
-      "  * OS:      #c{$os}" \
-      "  * VERSION: #c{$version}" \
-      "  * URL:     #c{$url}" \
-      "  * SHA1:    #c{$sha1}" \
-      ""
-    return 0
-  fi
-  describe "" \
-    "#G{Initiating upload of }#C{$type}#G{ stemcell to the }#M{$GENESIS_ENVIRONMENT}#G{ BOSH Director:}" \
-    "  * CPI:     #c{$cpi}" \
-    "  * OS:      #c{$os}" \
-    "  * VERSION: #c{$version}" \
-    "  * URL:     #c{$url}" \
-    "  * SHA1:    #c{$sha1}" \
-    ""
-
-  BOSH_ENVIRONMENT=$BOSH_URL \
-    BOSH_CA_CERT=$(safe read "${GENESIS_SECRETS_BASE}ssl/ca:certificate") \
-    BOSH_CLIENT="admin" \
-    BOSH_CLIENT_SECRET="$(safe read "${GENESIS_SECRETS_BASE}users/admin:password")" \
-    bosh "upload-stemcell${fix}" --sha1 "$sha1" "$url"
-  return $?
-}
-
-upload_stemcells() {
-  # Determine cpi
-  local cpi prev_cpi prev_cpi_feature want
-  for want in ${GENESIS_REQUESTED_FEATURES}; do
-    case "$want" in
-      aws|aws-cpi)              cpi="aws-xen-hvm" ;;
-      azure|azure-cpi)          cpi="azure-hyperv" ;;
-      google|google-cpi)        cpi="google-kvm" ;;
-      openstack|openstack-cpi)  cpi="openstack-kvm" ;;
-      vsphere|vpshere-cpi)      cpi="vsphere-esxi" ;;
-      warden|warden-cpi)        cpi="warden-boshlite" ;;
-    esac
-    if [[ -n "$cpi" ]] ; then
-      if [[ -n "${prev_cpi:-}" && "$prev_cpi" != "$cpi" ]] ; then
-        describe >&2 \
-          "#R{[CONFLICT]} Features '$prev_cpi_feature' and '$want' both correspond to a" \
-          "different CPI, using different stemcell types ($prev_cpi and $cpi " \
-          "respectively) -- Cannot continue."
-        exit 1
-      fi
-      prev_cpi_feature="$want"
-      prev_cpi="$cpi"
-    fi
-  done
-
-  if [[ -z "$cpi" ]] ; then
-    describe >&2 "#R{[ERROR]} No CPI feature defined -- cannot continue.";
-    exit 1
-  fi
-
-  local fix="" os="ubuntu-xenial" type="regular" type_s="full" noupload=""
-  local stemcells
-  declare -a versions
-  versions=()
-  while test $# -gt 0 ; do
-    case "$1" in
-      --get-url) noupload="1" ;;
-      --fix)     fix=" --fix" ;;
-      --os)      os="$2"; shift;;
-      --light)   type=type_s="light";;
-      --*)       describe "#R{[ERROR]} Bad option $1" && exit 1 ;;
-      *)         if [[ "$1" =~ .*@.* ]]; then versions+=("$1"); else versions+=("$os@$1"); fi;;
-    esac
-    shift
-  done
-
-  if [[ ${#versions[@]} -gt 0 ]] ; then
-    declare -a oses
-    declare -a stemcells_for_oses
-    local req
-    for req in "${versions[@]}" ; do
-      IFS="@" read -r req_os req_version <<< "$req"
-      i=0; while [[ $i -lt ${#oses[@]} ]] ; do
-        [[ ${oses[$i]} == "$req_os" ]] && break
-        ((i++))
-      done
-      set +u # bash can't handle empty arrays
-      if  [[ $i -eq ${#oses[@]} ]] ; then
-        oses+=("$req_os")
-        target="bosh-$cpi-$req_os-go_agent"
-        stemcells_for_oses+=("$(curl -s "https://bosh.io/api/v1/stemcells/${target}?all=0")")
-      fi
-      set -u
-
-      # Upload specified stemcells
-      local pattern match version url sha1
-      # shellcheck disable=2001
-      pattern="$(echo "$req_version" | sed -e 's/\.latest$/\.[0-9]+/')"
-      match="$( \
-        echo "${stemcells_for_oses[$i]}" | \
-        jq --arg re "^$pattern\$" --arg t "$type" '.[] | select((.version|test($re)) and (.|keys|index($t)))' | \
-        jq -Ms '.')"
-      version="$(echo "$match" | jq -Mr '.[] | .version' | sort -n -t. -k1 -k2 -k3 -k4| tail -n1)"
-      if [[ -z "$version" ]] ; then
-        describe "#R{[ERROR]} No $type_s version found matching $req_version for OS $req_os"
-      else
-        if [[ "$version" != "$req_version" ]] ; then
-          describe "Using best match to #C{$req_version}: #G{$version}"
-        fi
-        upload_stemcell "$req_os" "$cpi" "$version" "$fix" "$match" "$type" "$noupload"
-      fi
-    done
-  else
-    target="bosh-$cpi-$os-go_agent"
-    stemcells="$(curl -s "https://bosh.io/api/v1/stemcells/${target}?all=0")"
-    while true; do
-      opts=()
-      while read -r count major ; do
-        opts+=("-o" "[$major] $major.x ($count minor versions available)")
-      done <<< "$(echo "$stemcells" | jq -r --arg t "$type" '.[] | select(.|keys|index($t)) | .version' | cut -d. -f1 | sort -nr | uniq -c)"
-      major_sc_version= # Assigned below
-      prompt_for major_sc_version "select" "Select the release family for the $cpi $os stemcell you wish to upload:" "${opts[@]}"
-
-      opts=()
-      while read -r v ; do
-        opts+=("-o" "$v")
-      done <<< "$(echo "$stemcells" | jq -r '.[] | .version' | grep "^$major_sc_version\\(\\.\\|$\\)" | sort -rn -t. -k2 -k3 -k4)"
-      prompt_for version "select" "Select one of the available $major_sc_version.x versions:" "${opts[@]}"
-      upload_stemcell "$os" "$cpi" "$version" "$fix" "$stemcells" "$type" "$noupload"
-      rc=$?
-      continue= # Assigned below
-      prompt_for continue boolean "Upload another?" --default "no"
-      [[ "$continue" == "true" ]] || exit $rc
-    done
-  fi
-}
-
 credhub_login() {
   # Check for credhub command
-  command -v credhub > /dev/null 2>&1 || __bail "Command 'credhub' not found.  Please install from https://github.com/cloudfoundry-incubator/credhub-cli"
+  command -v credhub > /dev/null 2>&1 || bail "Command 'credhub' not found.  Please install from https://github.com/cloudfoundry-incubator/credhub-cli"
 
   # Update api target with correct ca's
   unset CREDHUB_SECRET
@@ -242,74 +103,213 @@ vault_proxy_login() {
   exit 1
 }
 
-list() {
-  describe "$(cat <<EOF
-The following addons are defined:
+#
+# Stemcell Hanlding
+#
 
-  alias                Set up a local bosh alias for a director
+# Default values for stemcell processing
+stemcell_os='ubuntu-xenial'
+stemcell_type='regular'
+stemcell_download_locally_for_upload=''
+stemcell_upload_dryrun=''
+stemcell_upload_fix=''
 
-  login                Log into an (aliased) director
+declare -a stemcell_versions; stemcell_versions=()
 
-  upload-stemcells     Upload the appropriate BOSH stemcells. Supports the
-                       following options and arguments:
+stemcells() {
+  action="$1"
+  [[ "$stemcell_type" == "regular" ]] && type_s="full" || type_s="$stemcell_type"
 
-    --fix              upload the stemcell even if its already uploaded
-    --os <str>         use the os <str> (defaults to ubuntu-xenial)
-    --light            use light stemcells instead of full ones
+  # Determine cpi
+  local cpi prev_cpi prev_cpi_feature want
+  for want in ${GENESIS_REQUESTED_FEATURES}; do
+    case "$want" in
+      aws|aws-cpi)              cpi="aws-xen-hvm" ;;
+      azure|azure-cpi)          cpi="azure-hyperv" ;;
+      google|google-cpi)        cpi="google-kvm" ;;
+      openstack|openstack-cpi)  cpi="openstack-kvm" ;;
+      vsphere|vpshere-cpi)      cpi="vsphere-esxi" ;;
+      warden|warden-cpi)        cpi="warden-boshlite" ;;
+    esac
+    if [[ -n "$cpi" ]] ; then
+      if [[ -n "${prev_cpi:-}" && "$prev_cpi" != "$cpi" ]] ; then
+        describe >&2 \
+          "#R{[CONFLICT]} Features '$prev_cpi_feature' and '$want' both correspond to a" \
+          "different CPI, using different stemcell types ($prev_cpi and $cpi " \
+          "respectively) -- Cannot continue."
+        exit 1
+      fi
+      prev_cpi_feature="$want"
+      prev_cpi="$cpi"
+    fi
+  done
 
-    <version>...       specify one or more versions of default or last
-                       specified --os option
-
-    <os>@<version>...  specify one or more versions of the given OS
-
-                       Will be interactive if no version is specified
-
-  runtime-config       Generate a base runtime config and upload it
-
-  credhub-login        Target and log in to credhub on this bosh director
-
-EOF
-)"
-  if want_feature vault-credhub-proxy; then
-    echo "  vault-proxy-login    Target and log into credhub via vault proxy using safe"
-    echo
+  if [[ -z "$cpi" ]] ; then
+    describe >&2 "#R{[ERROR]} No CPI feature defined -- cannot continue.";
+    exit 1
   fi
 
+  if [[ ${#stemcell_versions[@]} -gt 0 ]] ; then
+    declare -a oses; oses=()
+    declare -a stemcells_for_oses; stemcells_for_oses=()
+    local req
+    for req in "${stemcell_versions[@]}" ; do
+      if [[ -f "$GENESIS_CALLER_DIR/$req" && "$action" == "upload" ]] ; then
+        __stemcell_upload "$GENESIS_CALLER_DIR/$req"
+      else
+        IFS="@" read -r req_os req_version <<< "$req"
+        i=0; while [[ $i -lt ${#oses[@]} ]] ; do
+          [[ ${oses[$i]} == "$req_os" ]] && break
+          ((i++))
+        done
+        if  [[ $i -eq ${#oses[@]} ]] ; then
+          oses+=("$req_os")
+          target="bosh-$cpi-$req_os-go_agent"
+          stemcells_for_oses+=("$(curl -s "https://bosh.io/api/v1/stemcells/${target}?all=0")")
+        fi
+
+        # Get specified stemcells
+        local pattern match version url sha1
+        # shellcheck disable=2001
+        pattern="$(echo "$req_version" | sed -e 's/\.latest$/\.[0-9]+/')"
+        match="$( \
+          echo "${stemcells_for_oses[$i]}" | \
+          jq --arg re "^$pattern\$" --arg t "$stemcell_type" '.[] | select((.version|test($re)) and (.|keys|index($t)))' | \
+          jq -Ms '.')"
+        version="$(echo "$match" | jq -Mr '.[] | .version' | sort -n -t. -k1 -k2 -k3 -k4| tail -n1)"
+        if [[ -z "$version" ]] ; then
+          describe "#R{[ERROR]} No $type_s version found matching $req_version for OS $req_os"
+        else
+          if [[ "$version" != "$req_version" ]] ; then
+            describe "Using best match to #C{$req_version}: #G{$version}"
+          fi
+          __stemcell_process_remote "$action" "$cpi" "$req_os" "$version" "$match" "$type_s"
+        fi
+      fi
+    done
+  else
+    declare -a opts
+    target="bosh-$cpi-$stemcell_os-go_agent"
+    describe "" "Fetching a list of available #c{$type_s} #g{$stemcell_os} stemcells for #y{$cpi} from #m{bosh.io}"
+    stemcells="$(curl -s "https://bosh.io/api/v1/stemcells/${target}?all=0")"
+    while true; do
+      opts=()
+      while read -r count major ; do
+        opts+=("-o" "[$major] $major.x ($count minor versions available)")
+      done <<< "$(echo "$stemcells" | jq -r --arg t "$stemcell_type" '.[] | select(.|keys|index($t)) | .version' | cut -d. -f1 | sort -nr | uniq -c)"
+      if [[ "${#opts[@]}" -lt 0 ]] ; then
+        __bail "No #C{$type_s} stemcells found for $cpi $stemcell_os.  Please try a different type or OS."
+      fi
+      major_sc_version= # Assigned below
+      prompt_for major_sc_version "select" "Select the release family for the stemcell you wish to $action:" "${opts[@]}"
+
+      opts=()
+      while read -r v ; do
+        opts+=("-o" "$v")
+      done <<< "$(echo "$stemcells" | jq -r '.[] | .version' | grep "^$major_sc_version\\(\\.\\|$\\)" | sort -rn -t. -k2 -k3 -k4)"
+      prompt_for version "select" "Select one of the available $major_sc_version.x versions:" "${opts[@]}"
+      __stemcell_process_remote "$action" "$stemcell_os" "$cpi" "$version" "$stemcells" "$type_s"
+      rc=$?
+      continue= # Assigned below
+      prompt_for continue boolean "Another $action [y|n]?" --default "no"
+      [[ "$continue" == "true" ]] || exit $rc
+    done
+  fi
 }
 
-case $GENESIS_ADDON_SCRIPT in
-list)
-  list
-  exit 0
-  ;;
+__stemcell_process_remote() {
+  local url sha1 ext msg dry_run_msg action="$1" os="$2" cpi="$3" version="$4" data="$5" type="$6"
+  read -r url sha1 <<< "$(jq -r --arg t "$stemcell_type" --arg v "$version" '.[] | select(.version == $v)| to_entries[] | select(.key == $t).value  | .url + " " + .sha1' <<<"$data")"
+  # shellcheck disable=SC2001
+  ext="$(echo "$url" | sed -e 's/^.*-go_agent\.//')"
 
-alias)
-  setup_alias
-  ;;
+  if [[ "$action" == 'download' ]] ; then
+    file="$GENESIS_CALLER_DIR/$cpi-$os-$version-$type.$ext"
+    __stemcell_describe_remote "#G{Downloading }#c{$type}#G{ stemcell as }#M{$(humanize_path "$file")}" "$cpi" "$os" "$version" "$url" "$sha1"
+    __stemcell_download "$file" "$url" "$sha1"
+    return
+  fi
 
-login)
-  setup_alias >/dev/null
-  login
-  ;;
+  if [[ -n "$stemcell_download_locally_for_upload" ]]; then
+    msg="#G{Downloading }#c{$type}#G{ stemcell for local upload to the }#M{$GENESIS_ENVIRONMENT}#G{ BOSH Director:}"
+    dry_run_msg="not downloading stemcell or uploading it to BOSH director"
+  else
+    msg="#G{Initializing remote upload of }#C{$type}#G{ stemcell to the }#M{$GENESIS_ENVIRONMENT}#G{ BOSH Director:}"
+    dry_run_msg="not uploading to BOSH director"
+  fi
+  __stemcell_describe_remote "$msg" "$cpi" "$os" "$version" "$url" "$sha1"
 
-logout)
-  setup_alias >/dev/null
-  bosh -e "$GENESIS_ENVIRONMENT" logout
-  ;;
+  if [[ -n "$stemcell_upload_dryrun" ]] ; then
+    describe "#Y{Option --dry-run specified - $dry_run_msg}"
+    return
+  fi
 
-vault-proxy-login)
-  vault_proxy_login
-  ;;
+  if [[ -n "$stemcell_download_locally_for_upload" ]] ; then
+    mkdir -p 'stemcells'
+    file="stemcells/$cpi-$os-$version-$type.$ext"
+    [[ -f "$file" ]] && rm -f "$file"
+    __stemcell_download "$file" "$url" "$sha1"
+    __stemcell_upload "$file"
+    describe "Cleaning up temporary download"
+    rm -f "$file"
+  else
+    __stemcell_upload "$url" "$sha1"
+  fi
+}
 
-credhub-login)
-  credhub_login
-  ;;
+__stemcell_describe_remote() {
+describe "" "$1" \
+  "  * CPI:     #C{$2}" \
+  "  * OS:      #C{$3}" \
+  "  * VERSION: #C{$4}" \
+  "  * URL:     #C{$5}" \
+  "  * SHA1:    #C{$6}" \
+  ""
+}
 
-upload-stemcells|us)
-  upload_stemcells "$@"
-  ;;
+__stemcell_upload() {
+  local url="$1"
+  declare -a bosh_args; bosh_args=("upload-stemcell")
+  [[ -n "$stemcell_upload_fix" ]] && bosh_args+=("--fix")
+  [[ "${#@}" -gt 1 ]] && bosh_args+=("--sha1" "$2")
+  bosh_args+=("$url")
+  describe "Starting upload:"
+  BOSH_ENVIRONMENT=$BOSH_URL \
+    BOSH_CA_CERT=$(safe read "${GENESIS_SECRETS_BASE}ssl/ca:certificate") \
+    BOSH_CLIENT="admin" \
+    BOSH_CLIENT_SECRET="$(safe read "${GENESIS_SECRETS_BASE}users/admin:password")" \
+    bosh "${bosh_args[@]}"
+  return $?
+}
 
-runtime-config|rc)
+__stemcell_download() {
+  local file="$1" url="$2" sha1="$3"
+  if [[ -f "$file" ]] ; then
+    describe "#Y{File $file already exists - cowardly refusing to overwrite it!}"
+    return
+  fi
+  describe "#G{Starting download:}"
+  if curl -SLo "$file" "$url" ; then
+    sha1sum="$(command -v sha1sum || true)"
+    [[ -n "$sha1sum" ]] || sha1sum="$(command -v shasum || true)"
+    if [[ -n "$sha1sum" ]] ; then
+      if [[ "$($sha1sum "$file" | cut -d ' ' -f1)" == "$sha1" ]] ; then
+        describe "" "#G{Download successful - SHA1 digest matches!}"
+      else
+        describe "" "#R{Download failed - SHA1 digest does not match!}"
+        return 1
+      fi
+    else
+      describe "" "#Y{Download completed, but cannot verify SHA1 due to missing sha1sum/shasum executable}"
+    fi
+  else
+    describe "" "#R{Download failed!}"
+    return 1
+  fi
+  return 0
+}
+
+runtime_config() {
   describe "" \
     "The \`netop' user is a local administrator account configured with" \
     "a 4096-bit RSA SSH key for authentication.  It can be used to perform" \
@@ -390,6 +390,123 @@ runtime-config|rc)
                      echo '  - (( delete "genesis-local-users" ))')
     )
   fi
+}
+
+list() {
+  describe "$(cat <<EOF
+The following addons are defined:
+
+  alias                Set up a local bosh alias for a director
+
+  login                Log into an (aliased) director
+
+  upload-stemcells     Upload the appropriate BOSH stemcells. Supports the
+                       following options and arguments:
+
+    --dl               download the stemcell file to the local machine then
+                       upload it.  This may be necessary if the BOSH director
+                       does not have direct access to the internet.
+
+    --fix              upload the stemcell even if its already uploaded
+
+    --os <str>         use the os <str> (defaults to ubuntu-xenial)
+
+    --light            use light stemcells instead of full ones
+
+    --dry-run          provide details on the listed or selected stemcells, but
+                       dont upload them to the director.
+
+    <version>...       specify one or more versions of default or last
+                       specified --os option
+
+    <os>@<version>...  specify one or more versions of the given OS
+
+    <file>...          specify one or more local stemcell file
+
+                       Version, os@version, and files can be mixed in a single
+                       call.  Will be interactive if no version is specified.
+
+  download-stemcells   Download stemcells that will work on this BOSH director.
+                       Supports the same arguments as 'upload-stemcells' except
+                      --fix, --dry-run and --dl.
+
+  runtime-config       Generate a base runtime config and upload it
+
+  credhub-login        Target and log in to credhub on this bosh director
+
+EOF
+)"
+  if want_feature vault-credhub-proxy; then
+    echo "  vault-proxy-login    Target and log into credhub via vault proxy using safe"
+    echo
+  fi
+
+}
+
+case $GENESIS_ADDON_SCRIPT in
+list)
+  list
+  exit 0
+  ;;
+
+alias)
+  setup_alias
+  ;;
+
+login)
+  setup_alias >/dev/null
+  login
+  ;;
+
+logout)
+  setup_alias >/dev/null
+  bosh -e "$GENESIS_ENVIRONMENT" logout
+  ;;
+
+vault-proxy-login)
+  vault_proxy_login
+  ;;
+
+credhub-login)
+  credhub_login
+  ;;
+
+upload-stemcells|us)
+  #process options
+  while test $# -gt 0 ; do
+    case "$1" in
+      --dl)       stemcell_download_locally_for_upload=1 ;;
+      --dry-run)  stemcell_upload_dryrun=1 ;;
+      --fix)      stemcell_upload_fix=1 ;;
+      --os)       stemcell_os="$2"; shift ;;
+      --light)    stemcell_type="light" ;;
+      --*)        describe "#R{[ERROR]} Bad option $1" && exit 1 ;;
+      *)          if [[ -f "$GENESIS_CALLER_DIR/$1" || "$1" =~ .*@.* ]]; then
+                    stemcell_versions+=("$1")
+                  else
+                    stemcell_versions+=("$stemcell_os@$1")
+                  fi;;
+    esac
+    shift
+  done
+  stemcells upload
+  ;;
+
+download-stemcells|ds)
+  while test $# -gt 0 ; do
+    case "$1" in
+      --os)      stemcell_os="$2"; shift ;;
+      --light)   stemcell_type="light" ;;
+      --*)       describe "#R{[ERROR]} Bad option $1" && exit 1 ;;
+      *)         if [[ -f "$1" || "$1" =~ .*@.* ]]; then stemcell_versions+=("$1"); else stemcell_versions+=("$stemcell_os@$1"); fi;;
+    esac
+    shift
+  done
+  stemcells download "$@"
+  ;;
+
+runtime-config|rc)
+  runtime_config "$@"
   ;;
 
 ssh) # DO NOT LIST THIS IN 'list'...
