add iam instance profile feature

diff --git a/hooks/blueprint b/hooks/blueprint
--- a/hooks/blueprint
+++ b/hooks/blueprint
@@ -7,7 +7,8 @@ validate_features aws azure google openstack vsphere warden \
                   aws-cpi azure-cpi google-cpi openstack-cpi vsphere-cpi warden-cpi \
                   aws-init azure-init google-init openstack-init vsphere-init bosh-init \
                   proxy credhub shield bosh proto skip-op-users registry vault-credhub-proxy \
-                  external-db external-db-ca external-db-no-tls s3-blobstore
+                  external-db external-db-ca external-db-no-tls s3-blobstore \
+                  iam-instance-profile
 
 #
 # We always start out with the skeleton of a BOSH deployment,
@@ -66,6 +67,24 @@ for want in ${GENESIS_REQUESTED_FEATURES}; do
       merge+=(
         manifests/addons/vault-credhub-proxy.yml \
       )
+    fi
+
+    if want_feature iam-instance-profile; then
+      if [[ $want != "aws" ]]; then
+        printf >&2 "Cannot use IAM instance profiles if not deploying to AWS"
+        exit 2
+      fi
+
+      merge+=(
+        manifests/addons/iam-profile.yml
+      )
+
+      if want_feature proto; then
+        merge+=(
+          manifests/addons/proto-iam-profile.yml
+        )    
+      fi
+
     fi
 
     if want_feature external-db; then
