merge external-db-ca into external-db (#89)
* merge external-db-ca into external-db

* Update deprecation message to reflect splitting of external-db feature

* Don't include ca if no-tls requested

diff --git a/hooks/blueprint b/hooks/blueprint
--- a/hooks/blueprint
+++ b/hooks/blueprint
@@ -91,8 +91,15 @@ for want in ${GENESIS_REQUESTED_FEATURES}; do
     if want_feature external-db || want_feature external-db-mysql || want_feature external-db-postgres; then
       merge+=( 
         manifests/addons/external-db-internal-db-cleanup.yml \
-        manifests/addons/external-db.yml 
+        manifests/addons/external-db.yml \
       )
+
+      if ! want_feature external-db-no-tls; then
+        merge+=(
+          manifests/addons/external-db-ca.yml 
+        )
+      fi
+
       if want_feature external-db-mysql; then
         merge+=(
           manifests/addons/external-db-mysql.yml
@@ -103,10 +110,9 @@ for want in ${GENESIS_REQUESTED_FEATURES}; do
           manifests/addons/external-db-no-tls.yml
         )
       elif want_feature external-db-ca; then
-        merge+=( 
-          manifests/addons/external-db-ca.yml 
-        )
-
+        echo 'The BOSH director actually cannot be deployed without specifying an external CA' \
+          'and, consequently, this feature has been merged into `external-db-postgres` and' \
+          '`external-db-mysql`, respectively. You can remove this feature without any issues.' >&2
       fi
     fi
 
